@baseUrl=http://localhost:5000/api
@nameSource=posts

#
GET {{baseUrl}}/{{nameSource}} HTTP/1.1
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MWNiMjRmNTg3ZTAwYzE5M2EwMDk5NDMiLCJpYXQiOjE2NDA3MDMzNjd9.rMCmWlBwTVaMNEzjh7ko3R1jJb_XfAQXT-TilV9ikTE
###

# Test Api
POST {{baseUrl}}/{{nameSource}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MWNiMjRmNTg3ZTAwYzE5M2EwMDk5NDMiLCJpYXQiOjE2NDA3MDMzNjd9.rMCmWlBwTVaMNEzjh7ko3R1jJb_XfAQXT-TilV9ikTE

{
  "title": "hello 03",
  "description": "Day la description 03"
}
###