@baseUrl=http://localhost:5000/api
@nameSource=posts

#
GET {{baseUrl}}/{{nameSource}} HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MWNjNzMwMzFiMWExODQ1YTA2YjM3MGQiLCJpYXQiOjE2NDA4NTEzODV9.o2bOZtrupJkSItnrRBA1Z6WVJtGM1bixaVSpKqVdFMg
###

# Test Api
POST {{baseUrl}}/{{nameSource}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MWNjNzMwMzFiMWExODQ1YTA2YjM3MGQiLCJpYXQiOjE2NDA3ODg3Mzl9.43eGeU7b77TGr7ZP9lJGjLhGSnaiTGCgeJY05VyCOWk

{
  "title": "hello 01",
  "description": "Day la description 01"
}
###

#
DELETE {{baseUrl}}/{{nameSource}}/61cd4a71221713189bb24cc3 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MWNjNzMwMzFiMWExODQ1YTA2YjM3MGQiLCJpYXQiOjE2NDA4NTEzODV9.o2bOZtrupJkSItnrRBA1Z6WVJtGM1bixaVSpKqVdFMg
###