@baseUrl=http://localhost:5000/api
@nameSource=posts

#
GET {{baseUrl}}/{{nameSource}} HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MWM2YzhlMThlYTY4ZDlkMGM2NmE5NGEiLCJpYXQiOjE2NDA0MjIyOTJ9.sostSz6vz5al_YYYQ76_YoQUgGO8EBEMjgTYq6V9ERc
###

# Test Api
POST {{baseUrl}}/{{nameSource}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MWM2YzhlMThlYTY4ZDlkMGM2NmE5NGEiLCJpYXQiOjE2NDA0MjIyOTJ9.sostSz6vz5al_YYYQ76_YoQUgGO8EBEMjgTYq6V9ERc

{
  "title": "hello"
}
###